### ISSUE TITLE
Implement rotateArrayLeft

### ISSUE THREAD

**Issue by sadarshannaiynar** [rgehan/hacktoberfest-2k18-katas#259] opened 2018-10-05 02:55 UTC
# rotateArrayLeft

### Link to the PR that adds this test case:
#258 

### Where to implement:
`src/rotateArrayLeft.js`

### Where are the tests:
`src/rotateArrayLeft.test.js`

### Description (optional):
Rotate an array to the left by the rotation factor specified

Array: `[1, 2, 3, 4, 5]`
Rotation Factor: 3
Rotated Array `[4, 5, 1, 2, 3]`

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by niralpokal** [comment] 2018-10-05 04:34
Can I take this one?

**Comment by sadarshannaiynar** [comment] 2018-10-05 05:29
> Can I take this one?

@niralpokal Sure go ahead. :+1:

**Comment by rgehan** [comment] 2018-10-05 06:57
assign: @niralpokal

**Comment by s22su** [comment] 2018-10-05 07:43
@rgehan this is actually duplicate of my kata in #243

**Comment by rgehan** [comment] 2018-10-05 11:59
Oh yeah, closing it.

**Closed by rgehan** 2018-10-05 11:59 UTC
Labels: assigned, hacktoberfest
